# Generated by Django 6.0.7 on 2026-07-13 03:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='알러지명')),
            ],
            options={
                'verbose_name': '알러지',
                'verbose_name_plural': '알러지',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='선호도')),
            ],
            options={
                'verbose_name': '사용자 선호도',
                'verbose_name_plural': '사용자 선호도',
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_users', to='accounts.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 알러지',
                'verbose_name_plural': '사용자 알러지',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserAllergy', to='accounts.allergy'),
        ),
    ]
