# Generated by Django 6.0.7 on 2026-07-13 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_allergy_userpreference_userallergy_user_allergies'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='menus.cuisine'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userallergy',
            constraint=models.UniqueConstraint(fields=('user', 'allergy'), name='uniq_user_allergy'),
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.UniqueConstraint(fields=('user', 'cuisine'), name='uniq_user_cuisine'),
        ),
    ]
