# Generated by Django 6.0.7 on 2026-07-20 04:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('food', '음식 후기'), ('place', '음식점 후기')], default='food', max_length=10, verbose_name='후기 종류')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='reviews/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menus.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리뷰 좋아요',
                'verbose_name_plural': '리뷰 좋아요',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', through='reviews.ReviewLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='조회 시각')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '후기 조회 기록',
                'verbose_name_plural': '후기 조회 기록',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reviewlike',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='uniq_user_review_like'),
        ),
        migrations.AddConstraint(
            model_name='reviewview',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='uniq_user_review_view'),
        ),
    ]
