# Generated by Django 6.0.7 on 2026-07-16 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='조회 시각')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '후기 조회 기록',
                'verbose_name_plural': '후기 조회 기록',
                'ordering': ['-viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'review'), name='uniq_user_review_view')],
            },
        ),
    ]
