# Generated by Django 6.0.7 on 2026-07-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('food', '음식 후기'), ('place', '음식점 후기')], default='food', max_length=10, verbose_name='후기 종류'),
        ),
    ]
