"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 모든 설정값은 환경변수로 관리한다(CLAUDE.md 절대원칙 3).
# .env는 저장소에 커밋하지 않으며, .env.example을 참고해 각 서버에서 생성한다.
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Nginx(리버스 프록시) 뒤에서 TLS 종료. 원 요청이 https였는지는 Nginx가 넘겨주는
# X-Forwarded-Proto 헤더로 판별한다. 이게 있어야 request.is_secure() 등이 올바르게 동작.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# DEBUG=False + https 에서 폼 POST(로그인 등) CSRF 검사를 통과하려면 신뢰 오리진(scheme 포함)이 필요.
# 예: CSRF_TRUSTED_ORIGINS=https://192.168.32.74
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# HTTPS 강제 후, 브라우저가 다음부터 http:// 요청 자체를 자동으로 https://로 바꾸게 강제
# (ALB의 301 리다이렉트만으로는 첫 요청이 평문으로 나가는 SSL 스트리핑 취약점이 남기 때문)
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'accounts',
    'menus',
    'records',
    'reviews',
]

# 커스텀 User 모델(CLAUDE.md 절대원칙 6). 첫 migrate 전에 반드시 등록.
AUTH_USER_MODEL = 'accounts.User'

# 인증 리다이렉트
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'menus:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# MariaDB. 접속 정보는 모두 환경변수(CLAUDE.md 절대원칙 3, 4 - DB 계층 분리).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Cache & Session
# 세션은 앱 프로세스가 아닌 Redis에 저장한다(CLAUDE.md 절대원칙 1).
# Django 6 내장 Redis 캐시 백엔드를 사용한다.

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': env('REDIS_URL'),
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# ==========================================
# Static files (CSS, JavaScript, Images)
# ==========================================
# 1. 정적 파일 URL의 기본 형태 (CloudFront 주소가 있으면 거기로 연결)
if env('AWS_S3_CUSTOM_DOMAIN', default=None):
    STATIC_URL = f"https://{env('AWS_S3_CUSTOM_DOMAIN')}/static/"
    MEDIA_URL = f"https://{env('AWS_S3_CUSTOM_DOMAIN')}/media/"
else:
    STATIC_URL = 'static/'
    MEDIA_URL = env('MEDIA_URL', default='media/')

# 2. 장고가 CSS/JS 원본 파일을 찾을 위치 (기존 코드 유지)
STATICFILES_DIRS = [BASE_DIR / 'static']

# 3. 로컬 개발용(Fallback) 경로 (기존 코드 유지 - S3 쓸 땐 무시됨)
STATIC_ROOT = env('STATIC_ROOT', default=BASE_DIR / 'staticfiles')
MEDIA_ROOT = env('MEDIA_ROOT', default=BASE_DIR / 'media')


# ==========================================
# AWS S3 및 CloudFront 스토리지 설정 (새로 추가)
# ==========================================
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='ap-northeast-2')
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default=None)

# 4. 목적지를 S3로 변경하는 핵심 스위치
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "location": "media",
            "default_acl": None,         # 👈 S3 버킷의 퍼블릭 차단 정책과 충돌 방지
            "file_overwrite": True,
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "location": "static",
            "default_acl": None,         # 👈 S3 버킷의 퍼블릭 차단 정책과 충돌 방지
            "file_overwrite": True,
        },
    },
}
