# Generated by Django 6.0.7 on 2026-07-13 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('meal', models.CharField(choices=[('lunch', '점심'), ('dinner', '저녁')], max_length=10, verbose_name='끼니')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_records', to='menus.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '식사 기록',
                'verbose_name_plural': '식사 기록',
                'ordering': ['-date'],
            },
        ),
    ]
