# Generated by Django 6.0.7 on 2026-07-20 07:13

import django.db.models.deletion
from django.db import migrations, models


def link_exact_name_matches(apps, schema_editor):
    """기존 기록 중 food_name이 Menu.name과 '정확히' 일치하는 것만 menu FK 연결.

    표기가 갈린 것(돈가스 vs 돈카츠)은 자동으로 안 묶는다(오연결 위험). 정확일치만
    안전하게 백필하고, 나머지는 menu=None으로 두어 이후 사용자가 골라 정규화하게 한다.
    """
    MealRecord = apps.get_model('records', 'MealRecord')
    Menu = apps.get_model('menus', 'Menu')
    name_to_id = {}
    for mid, name in Menu.objects.values_list('id', 'name'):
        # 같은 이름 메뉴가 여러 개면 첫 번째만(카탈로그상 사실상 유니크)
        name_to_id.setdefault(name, mid)
    for rec in MealRecord.objects.filter(menu__isnull=True):
        mid = name_to_id.get(rec.food_name)
        if mid:
            MealRecord.objects.filter(pk=rec.pk).update(menu_id=mid)


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_records', to='menus.menu'),
        ),
        migrations.RunPython(link_exact_name_matches, migrations.RunPython.noop),
    ]
