# Generated by Django 6.0.7 on 2026-07-13 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_allergy_userpreference_userallergy_user_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='코스')),
            ],
            options={
                'verbose_name': '코스',
                'verbose_name_plural': '코스',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='종류')),
            ],
            options={
                'verbose_name': '요리 종류',
                'verbose_name_plural': '요리 종류',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='menus/', verbose_name='이미지')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('meal_time', models.CharField(choices=[('lunch', '점심'), ('dinner', '저녁'), ('any', '무관')], default='any', max_length=10, verbose_name='식사 시간')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='menus.course')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='menus.cuisine')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_menus', to='accounts.allergy')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_allergies', to='menus.menu')),
            ],
            options={
                'verbose_name': '메뉴 알러지',
                'verbose_name_plural': '메뉴 알러지',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='menus', through='menus.MenuAllergy', to='accounts.allergy'),
        ),
        migrations.AddConstraint(
            model_name='menuallergy',
            constraint=models.UniqueConstraint(fields=('menu', 'allergy'), name='uniq_menu_allergy'),
        ),
    ]
