# Generated by Django 6.0.7 on 2026-07-16 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='좋아요한 시각')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='menus.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '메뉴 좋아요',
                'verbose_name_plural': '메뉴 좋아요',
                'constraints': [models.UniqueConstraint(fields=('user', 'menu'), name='uniq_user_menu_like')],
            },
        ),
    ]
