# Generated by Django 6.0.7 on 2026-07-16 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_menus', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 한 사용자들'),
        ),
    ]
